routes/web.php
<?php

/*
 * Global Routes
 * Routes that are used between both frontend and backend.
 */

// Switch between the included languages
Route::get('lang/{lang}', 'LanguageController@swap');

/*
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    include_route_files(__DIR__ . '/frontend/');
});

/*
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    /*
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     * These routes can not be hit if the password is expired
     */
    include_route_files(__DIR__ . '/backend/');
});

app/Models/Closing/ClosingDetails.php
<?php

namespace App\Models\Closing;

use App\Models\Closing\Traits\Attribute\ClosingDetailsAttribute;
use App\Models\Closing\Traits\Event\ClosingDetailsEvent;
use App\Models\Closing\Traits\Relationship\ClosingDetailsRelationship;
use App\Models\Closing\Traits\Scope\ClosingDetailsScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


/**
 * Class ClosingDetails
 *
 * @package App\Models\Closing
 */
final class ClosingDetails extends Model
{
    use ClosingDetailsScope,
        ClosingDetailsAttribute,
        SoftDeletes,
        ClosingDetailsRelationship,
        ClosingDetailsEvent;

    /**
     * @var string
     */
    protected $table = 'setup_closing_details';
    /**
     * @var array
     */
    protected $guarded = [
        'id',
        'updated_at',
        '_token',
        '_method'
    ];
    /**
     * @var array
     */
    protected $dates = [
        'deleted_at',
    ];

    /**
     * @param  string  $eventName
     * @return string
     */
    public function getDescriptionForEvent(string $eventName): string
    {
        return 'Setup: Closing Balance: '.$this->trans_sl." is {$eventName}";
    }
}

app/Models/Closing/ClosingSummary.php
<?php

namespace App\Models\Closing;

use App\Models\Closing\Traits\Attribute\ClosingSummaryAttribute;
use App\Models\Closing\Traits\Event\ClosingSummaryEvent;
use App\Models\Closing\Traits\Relationship\ClosingSummaryRelationship;
use App\Models\Closing\Traits\Scope\ClosingSummaryScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


/**
 * Class ClosingSummary
 *
 * @package App\Models\Closing
 */
final class ClosingSummary extends Model
{
    use ClosingSummaryEvent,
        ClosingSummaryAttribute,
        SoftDeletes,
        ClosingSummaryRelationship,
        ClosingSummaryScope;

    /**
     * @var string
     */
    protected $table = 'setup_closing_summary';

    /**
     * @var array
     */
    protected $guarded = [
        'id',
        'updated_at',
        '_token',
        '_method'
    ];

    /**
     * @var array
     */
    protected $dates = [
        'deleted_at',
        'requisition_at',
        'transfer_at',
        'adjustment_at',
    ];

//    protected $primaryKey = 'sl';
//    public $keyType = "string";

    /**
     * @param  string  $eventName
     * @return string
     */
    public function getDescriptionForEvent(string $eventName): string
    {
        return 'Setup: Closing Balance: '.$this->sl." is {$eventName}";
    }
}

app/Models/Closing/Traits/Attribute/ClosingDetailsAttribute.php
<?php

namespace App\Models\Closing\Traits\Attribute;

/**
 * Class UserAttribute.
 */
trait ClosingDetailsAttribute
{
    /**
     * @return string
     */
    public function getStatusLabelAttribute()
    {
        if ($this->isActive()) {
            return "<label class='label label-success'>".$this->statuses->name.'</label>';
        }

        return "<label class='label label-danger'>".$this->statuses->name.'</label>';
    }

    /**
     * @return bool
     */
    public function isActive()
    {
        return $this->status == 1;
    }

    function getFullNameAttribute()
    {
        return $this->code.' || '.$this->name;
    }

    /**
     * @return string
     */
    public function getShowButtonAttribute()
    {
        return '<a href="'.route("admin.setup.transaction.invoice_terms.show",
                $this).'" class=""><i class="cus-application-view-detail" data-toggle="tooltip" data-placement="top" title="'.trans('buttons.general.crud.view').'"></i></a> ';
    }

    /**
     * @return string
     */
    public function getEditButtonAttribute()
    {
        return '<a href="'.route("admin.setup.transaction.invoice_terms.edit",
                $this).'" class=""><i class="cus-application-edit" data-toggle="tooltip" data-placement="top" title="'.trans('buttons.general.crud.edit').'"></i></a> ';
    }

    /**
     * @return string
     */
    public function getStatusButtonAttribute()
    {
        switch ($this->status) {
            case 2:
                return '<a href="'.route('admin.setup.transaction.invoice_terms.mark', [
                        $this,
                        1,
                    ]).'" class=""><i class="cus-control-play" data-toggle="tooltip" data-placement="top" title="'.trans('buttons.backend.access.users.activate').'"></i></a> ';
            // No break

            case 1:
                return '<a href="'.route('admin.setup.transaction.invoice_terms.mark', [
                        $this,
                        2,
                    ]).'" class=""><i class="cus-control-pause" data-toggle="tooltip" data-placement="top" title="'.trans('buttons.backend.access.users.deactivate').'"></i></a> ';
            // No break

            default:
                return '';
            // No break
        }
    }

    /**
     * @return string
     */
    public function getDeleteButtonAttribute()
    {
        return '<a href="'.route("admin.setup.transaction.invoice_terms.destroy", $this).'"
                 data-method="delete"
                 data-trans-button-cancel="'.trans('buttons.general.cancel').'"
                 data-trans-button-confirm="'.trans('buttons.general.crud.delete').'"
                 data-trans-title="'.trans('strings.backend.general.are_you_sure').'"
                 class=""><i class="cus-bin-closed" data-toggle="tooltip" data-placement="top" title="'.trans('buttons.general.crud.delete').'"></i></a> ';
    }

    /**
     * @return string
     */
    public function getRestoreButtonAttribute()
    {
        return '<a href="'.route("admin.setup.transaction.invoice_terms.restore",
                $this).'" name="restore_user" class=""><i class="cus-arrow-refresh" data-toggle="tooltip" data-placement="top" title="'.trans('buttons.general.crud.restore').'"></i></a> ';
    }

    /**
     * @return string
     */
    public function getDeletePermanentlyButtonAttribute()
    {
        return '<a href="'.route("admin.transaction.invoice_terms.delete-permanently",
                $this).'" name="delete_user_perm" class=""><i class="cus-bin-closed" data-toggle="tooltip" data-placement="top" title="'.trans('buttons.general.crud.delete_permanently').'"></i></a> ';
    }

    /**
     * @return string
     */
    public function getActionButtonsAttribute()
    {
        if ($this->trashed()) {
            return $this->restore_button.$this->delete_permanently_button;
        }

        return
            //  $this->show_button.
            // $this->edit_button.
            // $this->status_button.
            $this->delete_button;
    }
}

app/Models/Closing/Traits/Event/ClosingDetailsEvent.php
<?php

namespace App\Models\Closing\Traits\Event;

use Carbon\Carbon;

/**
 * Class UserRelationship.
 */
trait ClosingDetailsEvent
{
    public static function boot()
    {
        parent::boot();

        self::creating(function ($model) {
            $model->created_by = access()->user()->id;
            $model->created_at = Carbon::now();

        });

        self::updating(function ($model) {
            $model->updated_by = access()->user()->id;
            // $model->updated_by_name = $user->username;
            $model->updated_at = Carbon::now();
        });

        self::deleting(function ($model) {
            $model->deleted_by = access()->user()->id;
            //$model->deleted_by_name = $user->username;
            $model->deleted_at = Carbon::now();
        });
    }
}

app/Models/Closing/Traits/Event/ClosingSummaryEvent.php
<?php

namespace App\Models\Closing\Traits\Event;

use Carbon\Carbon;

/**
 * Class UserRelationship.
 */
trait ClosingSummaryEvent
{
    public static function boot()
    {
        parent::boot();

        self::creating(function ($model) {
            $model->created_by = access()->user()->id;
            $model->created_at = Carbon::now();

        });

        self::updating(function ($model) {
            $model->updated_by = access()->user()->id;
            // $model->updated_by_name = $user->username;
            $model->updated_at = Carbon::now();
        });

        self::deleting(function ($model) {
            $model->deleted_by = access()->user()->id;
            //$model->deleted_by_name = $user->username;
            $model->deleted_at = Carbon::now();
        });
    }
}

app/Http/Controllers/Backend/Setup/Bank/BankController.php
<?php

namespace App\Http\Controllers\Backend\Setup\Bank;


use App\Exceptions\GeneralException;
use App\Http\Controllers\BaseController;
use App\Repositories\Backend\Setup\Bank\BankRepository;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\View\View;
use Throwable;

/**
 * Class BankController
 *
 * @package App\Http\Controllers\Backend\Setup\Bank
 */
final class BankController extends BaseController
{
    /**
     * BankController constructor.
     *
     * @param  BankRepository  $bankRepository
     */
    public function __construct(BankRepository $bankRepository)
    {
        $this->repository = $bankRepository;

        $this->module_action = '';
        $this->module_parent = 'Setup';
        $this->module_name = 'banks';
        $this->module_icon = 'mdi-hospital-building';
        $this->module_route = 'admin.setup.'.$this->module_name;
        $this->module_view = 'backend.setup.'.$this->module_name;
    }

    /**
     * @return Factory|View
     */
    public function index()
    {
        $module_parent = $this->module_parent;
        $module_name = $this->module_name;
        $module_name_singular = str_singular($this->module_name);
        $module_icon = $this->module_icon;
        $module_action = 'index';
        $module_route = $this->module_route;
        $module_view = $this->module_view;

        $page_heading = $this->module_parent.' - View All';

        $$module_name = $this->repository->getAll();
        return view($module_view.'.'.$module_action,
            compact('module_name', $module_name, 'module_name_singular', 'module_parent', 'module_icon', 'page_heading',
                'module_action', 'module_view', 'module_route'));
    }

    /**
     * @return Factory|View
     */
    public function create()
    {
        $module_parent = $this->module_parent;
        $module_name = $this->module_name;
        $module_name_singular = str_singular($this->module_name);
        $module_icon = $this->module_icon;
        $module_action = 'create';
        $module_route = $this->module_route;
        $module_view = $this->module_view;

        $page_heading = $this->module_parent.' - Add New';

        return view($module_view.'.'.$module_action,
            compact('module_name', 'module_name_singular', 'module_parent', 'module_icon', 'page_heading',
                'module_action', 'module_view', 'module_route'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     * @throws Throwable
     */
    public function store(Request $request)
    {
        $module_route = $this->module_route;

        $this->repository->create([
            'data' => $request->except(['_token'])
        ]);

        return redirect()->route($module_route.'.index')->withFlashSuccess('Record successfully saved');
    }

    /**
     * Display the specified resource.
     *
     * @param $id
     * @return Response
     * @internal param int $id
     */
    public function show($id)
    {
        $module_parent = $this->module_parent;
        $module_name = $this->module_name;
        $module_name_singular = str_singular($this->module_name);
        $module_icon = $this->module_icon;
        $module_action = 'show';
        $module_route = $this->module_route;
        $module_view = $this->module_view;

        $page_heading = $this->module_parent.' - View';

        $$module_name_singular = $this->repository->find($id);

        return view($module_view.'.show',
            compact('module_name', $module_name_singular, 'module_name_singular', 'module_parent', 'module_icon',
                'page_heading', 'module_action', 'module_view', 'module_route'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $module_parent = $this->module_parent;
        $module_name = $this->module_name;
        $module_name_singular = str_singular($this->module_name);
        $module_icon = $this->module_icon;
        $module_action = 'edit';
        $module_route = $this->module_route;
        $module_view = $this->module_view;

        $page_heading = $this->module_parent.' - Edit';

        $$module_name_singular = $this->repository->find($id);

        return view($module_view.'.edit',
            compact('module_name', $module_name_singular, 'module_name_singular', 'module_parent', 'module_icon',
                'page_heading', 'module_action', 'module_view', 'module_route'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int      $id
     * @return Response
     * @throws Throwable
     */
    public function update($id, Request $request)
    {
        $module_route = $this->module_route;

        $this->repository->update($id, [
            'data' => $request->except(
                '_token',
                '_method'
            ),
        ]);

        return redirect()->route($module_route.'.index')->withFlashSuccess(trans('Record successfully updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     * @throws Throwable
     */
    public function destroy($id)
    {
        $module_route = $this->module_route;

        $this->repository->delete($id);

        return redirect()->route($module_route.'.deleted')->withFlashSuccess(trans('Record successfully deleted'));
    }

    /**
     * @param $id
     * @return mixed
     * @throws GeneralException
     * @throws Throwable
     */
    public function restore($id)
    {
        $module_route = $this->module_route;

        $this->repository->restore($id);

        return redirect()->route($module_route.'.index')->withFlashSuccess(trans('Record successfully restored'));
    }

    /**
     * @param $id
     * @return mixed
     * @throws GeneralException
     * @throws Throwable
     */
    public function delete($id)
    {
        $module_route = $this->module_route;
        $this->repository->forceDelete($id);

        return redirect()->route($module_route.'.deleted')->withFlashSuccess(trans('Records deleted permanently'));
    }

    /**
     * @param $id
     * @param $status
     * @return mixed
     * @throws GeneralException
     */
    public function mark($id, $status)
    {
        $module_route = $this->module_route;

        $this->repository->mark($id, $status);

        return redirect()->route($status === 1 ? $module_route.'.index' : $module_route.'.deactivated')->withFlashSuccess(trans('Records updated successfully'));
    }

    /**
     * @return Factory|View
     */
    public function getDeactivated()
    {
        $module_name = $this->module_name;
        $module_name_singular = str_singular($this->module_name);
        $module_action = 'deactivated';
        $module_route = $this->module_route;
        $module_parent = $this->module_parent;
        $module_view = $this->module_view;
        $module_icon = $this->module_icon;

        $page_heading = page_title($this->module_parent, $module_name, 'All Deactivated');

        $$module_name = $this->repository->getDeactivated();

        return view($module_view.'.deactivated', compact('module_name', $module_name,
            'module_name_singular', 'module_parent', 'module_icon', 'page_heading', 'module_action', 'module_view',
            'module_route'));
    }

    /**
     * @return Factory|View
     */
    public function trashed()
    {
        $module_name = $this->module_name;
        $module_name_singular = str_singular($this->module_name);
        $module_action = 'deleted';
        $module_route = $this->module_route;
        $module_parent = $this->module_parent;
        $module_view = $this->module_view;
        $module_icon = $this->module_icon;

        $page_heading = page_title($this->module_parent, $module_name, 'All Deleted');

        $$module_name = $this->repository->getDeleted();

        return view($module_view.'.deleted',
            compact('module_name', $module_name, 'module_name_singular', 'module_parent', 'module_icon', 'page_heading',
                'module_action', 'module_view', 'module_route'));
    }
}

resources/views/backend/setup/closings/create.blade.php
@extends ('backend.layouts.app')

@section ('title',$page_heading)

@section('after-styles')
    <style type="text/css">
        .input-group-addon {
            padding: 3px 5px !important;
        }

        .required {
            content: "*";
            position: absolute;
            top: 11px;
            right: 3px;
            font-size: 15px;
            color: red;
            font-weight: 700;
        }

        .input-group .required {
            right: -9px;
        }
    </style>
@endsection

@section('content')
    @component('includes.components.widget')
        @slot('title')
            {{ $page_heading }}
        @endslot

        @slot('action_buttons')
            @include($module_view.'.header-buttons')
        @endslot

        {{ Form::open(['route' => $module_route.'.store','files' => true, 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'post']) }}

        @include($module_view.'.form')

        <div class="row">
            <div class="col-lg-6">
                {!! Form::button(('<i class="fa fa-check fa-fw"></i>&nbsp;'.$module_action), ['class' => 'btn btn-success pull-right','type'=>'submit']) !!}
            </div>

            <div class="col-lg-6">
                {!! link_to(route($module_route.'.index'), ('<i class="fa fa-mail-reply"></i>&nbsp;'.trans('buttons.general.cancel')), ['class' => 'btn btn-danger pull-left'], null, false) !!}
            </div><!--col-lg-1-->
        </div><!--form control-->

        <br>
        {{ Form::close() }}

    @endcomponent
@endsection

@section('after-scripts')

    <script type="text/javascript">
        $(document).ready(function () {
            //add required

            $("input[required='required'], select").each(function () {
                $(this).before('<span class="required">*</span>');
            });

            var $pwdField = $("#pwdField");
            $pwdField.val($pwdField.data('value'));
            $("#pwdChk").on('click', function (e) {
                if (!$(this).prop('checked')) {
                    $pwdField.removeAttr('readonly');
                    $pwdField.val('');
                    $pwdField.focus();
                } else {
                    $pwdField.prop('readonly', true);
                    $pwdField.val($pwdField.data('value'));
                }
            });
        });
    </script>

@endsection

resources/views/backend/setup/closings/deactivated.blade.php
@extends ('backend.layouts.app')

@section ('title', $page_heading)

@section('after-styles')
    {{ Html::style("https://cdn.datatables.net/v/bs/dt-1.10.15/datatables.min.css") }}
@endsection

@section('page-header')
    <h1>
        {{ $page_heading }}
    </h1>
@endsection

@section('content')
    @component('includes.components.widget')
        @slot('title')
            {{ $page_heading }}
        @endslot

        @slot('action_buttons')
            @include($module_view.'.header-buttons')
        @endslot

        @component('includes.components.table',['class'=>'table table-condensed table-hover table-striped','id'=>''])
            @slot('thead')
                <th>#</th>
                <th>Name</th>
                <th>Code</th>
                <th>Status</th>
                <th>{{ trans('labels.general.actions') }}</th>
            @endslot

            @slot('tbody')
                @foreach($$module_name as $module_name)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td> {{ $module_name->name }}</td>
                        <td> {{ $module_name->code }}</td>
                        <td> {!! $module_name->status_label !!} </td>
                        <td> {!! $module_name->action_buttons !!}</td>
                    </tr>
                @endforeach
            @endslot
        @endcomponent

    @endcomponent

@endsection

@section('after-scripts')
    {{ Html::script("https://cdn.datatables.net/v/bs/dt-1.10.15/datatables.min.js") }}
    {{ Html::script("js/backend/plugin/datatables/dataTables-extend.js") }}

    <script>
        $(function () {
            $('#users-table').DataTable({
                dom: 'lfrtip',
                processing: false,
                serverSide: true,
                autoWidth: false,
                ajax: {
                    url: '{{ route("admin.access.user.get") }}',
                    type: 'post',
                    data: {status: 0, trashed: false},
                    error: function (xhr, err) {
                        if (err === 'parsererror')
                            location.reload();
                    }
                },
                columns: [
                    {data: 'last_name', name: '{{config('access.users_table')}}.last_name'},
                    {data: 'first_name', name: '{{config('access.users_table')}}.first_name'},
                    {data: 'email', name: '{{config('access.users_table')}}.email'},
                    {data: 'confirmed', name: '{{config('access.users_table')}}.confirmed'},
                    {data: 'roles', name: '{{config('access.roles_table')}}.name', sortable: false},
                    {data: 'created_at', name: '{{config('access.users_table')}}.created_at'},
                    {data: 'updated_at', name: '{{config('access.users_table')}}.updated_at'},
                    {data: 'actions', name: 'actions', searchable: false, sortable: false}
                ],
                order: [[0, "asc"]],
                searchDelay: 500
            });
        });
    </script>
@endsection

resources/views/backend/setup/closings/deleted.blade.php
@extends ('backend.layouts.app')

@section ('title', $page_heading)

@section('after-styles')
    {{ Html::style("https://cdn.datatables.net/v/bs/dt-1.10.15/datatables.min.css") }}
@endsection

@section('page-header')
    <h1>
        {{ $page_heading }}
    </h1>
@endsection

@section('content')
    @component('includes.components.widget')
        @slot('title')
            {{ $page_heading }}
        @endslot

        @slot('action_buttons')
            @include($module_view.'.header-buttons')
        @endslot

        @component('includes.components.table',['class'=>'table table-condensed table-hover table-striped','id'=>''])
            @slot('thead')
                <th>#</th>
                <th>Name</th>
                <th>Code</th>
                <th>Status</th>
                <th>{{ trans('labels.general.actions') }}</th>
            @endslot

            @slot('tbody')
                @foreach($$module_name as $module_name)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td> {{ $module_name->name }}</td>
                        <td> {{ $module_name->code }}</td>
                        <td> {!! $module_name->status_label !!} </td>
                        <td> {!! $module_name->action_buttons !!}</td>
                    </tr>
                @endforeach
            @endslot
        @endcomponent

    @endcomponent

@endsection

@section('after-scripts')
    {{ Html::script("https://cdn.datatables.net/v/bs/dt-1.10.15/datatables.min.js") }}
    {{ Html::script("js/backend/plugin/datatables/dataTables-extend.js") }}

    <script>
        $(function () {
            $('#users-table').DataTable({
                dom: 'lfrtip',
                processing: false,
                serverSide: true,
                autoWidth: false,
                ajax: {
                    url: '{{ route("admin.access.user.get") }}',
                    type: 'post',
                    data: {status: 0, trashed: true},
                    error: function (xhr, err) {
                        if (err === 'parsererror')
                            location.reload();
                    }
                },
                columns: [
                    {data: 'last_name', name: '{{config('access.users_table')}}.last_name'},
                    {data: 'first_name', name: '{{config('access.users_table')}}.first_name'},
                    {data: 'email', name: '{{config('access.users_table')}}.email'},
                    {data: 'confirmed', name: '{{config('access.users_table')}}.confirmed'},
                    {data: 'roles', name: '{{config('access.roles_table')}}.name', sortable: false},
                    {data: 'created_at', name: '{{config('access.users_table')}}.created_at'},
                    {data: 'updated_at', name: '{{config('access.users_table')}}.updated_at'},
                    {data: 'actions', name: 'actions', searchable: false, sortable: false}
                ],
                order: [[0, "asc"]],
                searchDelay: 500
            });
        });
    </script>
@endsection

resources/views/backend/setup/closings/header-buttons.blade.php
<div class="btn-group float-right">
    <a href="{{ route($module_route.".index") }}" class="btn  btn-alt-primary btn-sm" data-toggle="click-ripple"><i
                class="si si-grid"></i>&nbsp;All {{ title_case($module_name) }}</a>
    <a href="{{ route($module_route.".create") }}" class="btn  btn-alt-success btn-sm" data-toggle="click-ripple"><i
                class="si si-plus"></i>&nbsp;Add New</a>
</div><!--pull right-->

resources/views/backend/setup/closings/index.blade.php
@extends ('backend.layouts.app')

@section ('title', $page_heading)

@section('after-styles')
    {{ Html::style("https://cdn.datatables.net/v/bs/dt-1.10.15/datatables.min.css") }}
@endsection

@section('content')
    <div class="row">
        <!-- DOM dataTable -->
        <div class="col-md-12">
            @component('includes.components.widget')

                @slot('title')
                    {{ $page_heading }}
                @endslot

                @slot('action_buttons')
                    @include($module_view.'.header-buttons')
                @endslot

                {{--Widget body start--}}
                @component('includes.components.table',['class'=>'table table-condensed table-hover table-striped table-bordered','id'=>''])
                    @slot('thead')
                        <th class="text-center" style="font-size: 14px">SL</th>
                        <th class="text-right" style="font-size: 14px">Branch</th>
                        <th class="text-right" style="font-size: 14px">Collection</th>
                        <th class="text-right" style="font-size: 14px">Outstanding</th>
                        <th class="text-right" style="font-size: 14px">Cash Amount P/C</th>
                        <th class="text-right" style="font-size: 14px">Bank Amount P/C</th>


                        <th class="text-center">{{ __('labels.general.actions') }}</th>

                    @endslot

                    @slot('tbody')
                        @foreach($$module_name as $module_name)
                            @php
                                if($module_name->isApprove()){
                                   $bg = 'bg-success-light';
                                }else{
                                    $bg = '';
                                }
                            @endphp

                            <tr class= {{$bg}}>
                                <td class="text-center"
                                    style="font-weight: bold; color: #0d89ed">{{ $module_name->sl }}</td>
                                <td class="text-center"> {{ $module_name->branch_name }}</td>
                                @php
                                    $dtSumColl = $module_name->details->sum('collection');
                                    $dtSumOut = $module_name->details->sum('outstanding');
                                    $dtSumCash = $module_name->pc_cash_amount;
                                    $dtSumBank = $module_name->pc_bank_amount;
                                @endphp
                                <td class="text-right"> {{ $dtSumColl }}</td>
                                <td class="text-right"> {{ $dtSumOut }}</td>
                                <td class="text-right"> {{ $dtSumCash }}</td>
                                <td class="text-right"> {{ $dtSumBank }}</td>

                                <td> {!! $module_name->action_buttons !!}</td>

                            </tr>

                        @endforeach
                    @endslot
                @endcomponent

            @endcomponent
        </div><!-- END column -->
    </div><!-- .row -->
@endsection

@section('after-scripts')

@endsection